Algoritmo "Exemplo 3"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Carlos
// Descrição   : Escrever um algoritmo que gera e escreve os números ímpares entre 100 e 200.
// Autor(a)    : Gisele Leite de Deus
// Data atual  : 13/04/2023

Var

n: inteiro

Inicio

//Laço de Repetição "para...faça"
para n de 100 ate 200 faca
     se n % 2 <> 0 entao
       escreval("Os Impares são: ", n)
     fimse
fimpara

Fimalgoritmo
